baseurl: /
collections:
  tooltips: {output: false}
company_name: muellerzr
default_badges: {colab: true}
defaults:
- scope: {path: '', type: pages}
  values: {comments: true, layout: page, search: true, sidebar: home_sidebar, topnav: topnav}
- scope: {path: '', type: tooltips}
  values: {comments: true, layout: page, search: true, tooltip: true}
description: Taking fastai to the next level
exclude: [.idea/, .gitignore, vendor]
feedback_disable: true
github_editme_path: null
google_analytics: null
google_search: null
highlighter: rouge
kramdown: {auto_ids: true, hard_wrap: false, syntax_highlighter: rouge}
markdown: kramdown
output: web
plugins: [jekyll-remote-theme]
remote_theme: fastai/nbdev-jekyll-theme
repository: walkwithfastai/walkwithfastai.github.io
sidebars: [home_sidebar]
site_title: walkwithfastai
topnav_title: walkwithfastai
twitter_username: muellerzr
url: https://walkwithfastai.com
use_math: true
